-- Sembrar en la BD el contenido de las 6 sub-páginas de Máquinas que
-- nunca se guardaron ahí (solo existían como HTML estático) — sin esto,
-- el editor del admin aparece vacío para Fuga, Limpieza, Marcado,
-- Inspección, Celdas robóticas y Manufactura, con riesgo de que alguien
-- guarde ahí por accidente y borre el contenido real.
-- Run once: mysql -u dematiq_app -p dematiq_db < database/migrations/010_maquinas_seed.sql

USE dematiq_db;

INSERT INTO contenido (clave, valor) VALUES ('maqprob', '{"titulo":"Máquinas Probadoras de Fuga","subtitulo":"Probadoras de Fuga","tabs":[{"nombre":"Fuga de Gas","desc":"Detección y cuantificación de fugas gaseosas en recipientes herméticos y tuberías. Evaluamos la integridad de los contenedores bajo condiciones operativas reales, garantizando seguridad industrial y cumplimiento ambiental.","images":["assets\\/images\\/general\\/fuga.webp","assets\\/images\\/general\\/img1.webp"]},{"nombre":"Fuga de Helio","desc":"Pruebas de hermeticidad de alta sensibilidad mediante gas trazador en cámara de vacío. Identificamos microfugas imperceptibles por otros métodos, ideal para componentes críticos automotrices, aeroespaciales y de refrigeración.","images":["assets\\/images\\/general\\/img1.webp","assets\\/images\\/general\\/img2.webp"]},{"nombre":"Sniffer de Helio","desc":"Localización exacta de fugas mediante olfateo manual o automatizado del gas trazador acumulado. Permite inspeccionar puntos específicos de ensamble, uniones complejas y soldaduras con máxima precisión en tiempo real.","images":["assets\\/images\\/general\\/img2.webp","assets\\/images\\/general\\/img3.webp"]},{"nombre":"Burbuja","desc":"Detección de fugas por inmersión, observando el burbujeo que produce el aire al escapar de una pieza presurizada y sumergida en líquido. Método visual, económico y confiable para localizar el punto exacto de la fuga en componentes, uniones y soldaduras.","images":["assets\\/images\\/general\\/img3.webp","assets\\/images\\/general\\/img1.webp"]},{"nombre":"Flujo","desc":"Medición directa del caudal de aire que se escapa de una pieza a presión constante. Cuantifica el volumen de la fuga de forma instantánea, permitiendo una validación rápida y eficiente de conductos, mangueras y tuberías.","images":["assets\\/images\\/general\\/fuga.webp","assets\\/images\\/general\\/img1.webp"]},{"nombre":"Caída de Vacío","desc":"Evaluación de hermeticidad mediante la extracción de aire y el monitoreo del aumento de la presión absoluta. El ingreso de aire exterior revela fallas en el sellado, garantizando la calidad en empaques o componentes herméticos.","images":["assets\\/images\\/general\\/img1.webp","assets\\/images\\/general\\/img2.webp"]},{"nombre":"Caída de Presión","desc":"Presurización del componente y monitoreo de la pérdida de presión en un intervalo de tiempo. Es el método estándar más rápido, eficiente y confiable para el control de calidad en líneas de producción en masa.","images":["assets\\/images\\/general\\/img2.webp","assets\\/images\\/general\\/img3.webp"]}]}')
  ON DUPLICATE KEY UPDATE valor = VALUES(valor);

INSERT INTO contenido (clave, valor) VALUES ('maclim', '{"titulo":"Máquinas de Limpieza","subtitulo":"Limpieza","tabs":[{"nombre":"Aire de Alta Presión","desc":"Remoción seca de partículas, polvos y virutas mediante flujos de aire comprimido a gran velocidad. Limpieza eficiente y rápida, ideal para estaciones previas al ensamble final o procesos de inspección óptica.","images":["assets\\/images\\/general\\/limpieza.webp","assets\\/images\\/general\\/img1.webp"]},{"nombre":"Inmersión","desc":"Lavado uniforme mediante el sumergido completo de piezas en soluciones químicas industriales. Elimina contaminantes en todas las superficies internas y externas, siendo la solución ideal para componentes de geometría compleja.","images":["assets\\/images\\/general\\/img1.webp","assets\\/images\\/general\\/img2.webp"]},{"nombre":"Aspersión a Alta Presión","desc":"Proyección con fuerza de fluidos limpiadores a través de boquillas estratégicamente orientadas. El impacto mecánico remueve de manera eficaz grasas, aceites y suciedad incrustada en procesos de producción continua.","images":["assets\\/images\\/general\\/img2.webp","assets\\/images\\/general\\/img3.webp"]},{"nombre":"Ultrasonido","desc":"Limpieza microscópica mediante ondas acústicas de alta frecuencia que generan cavitación en medio líquido. Desprende la suciedad más difícil en áreas inaccesibles sin causar daños ni alterar el material de la pieza.","images":["assets\\/images\\/general\\/img3.webp","assets\\/images\\/general\\/img1.webp"]}]}')
  ON DUPLICATE KEY UPDATE valor = VALUES(valor);

INSERT INTO contenido (clave, valor) VALUES ('maqmar', '{"titulo":"Máquinas de Marcado","subtitulo":"Marcado","tabs":[{"nombre":"Marcado Láser","desc":"Grabado permanente de códigos, textos o logotipos mediante un haz de luz concentrado. Ofrece una definición extrema a altas velocidades en metales o plásticos, eliminando el uso de consumibles.","images":["assets\\/images\\/general\\/micro.webp","assets\\/images\\/general\\/img1.webp"]},{"nombre":"Micropercusión","desc":"Grabado profundo mediante impactos sucesivos de una punta de carburo neumática o eléctrica. Ideal para la identificación permanente de componentes expuestos a condiciones industriales severas o ambientes hostiles.","images":["assets\\/images\\/general\\/img1.webp","assets\\/images\\/general\\/img2.webp"]},{"nombre":"Inyección de Tinta","desc":"Codificación dinámica a alta velocidad sin contacto directo con la superficie del producto. Solución ágil para la impresión de fechas de caducidad, lotes, códigos de barras y textos variables en líneas de empaque.","images":["assets\\/images\\/general\\/img2.webp","assets\\/images\\/general\\/img3.webp"]},{"nombre":"Troquel","desc":"Estampado o corte de materiales mediante presión mecánica o hidráulica con una matriz predeterminada. Un método tradicional, rápido y de gran robustez para la identificación o preformado en serie de piezas metálicas.","images":["assets\\/images\\/general\\/img3.webp","assets\\/images\\/general\\/img1.webp"]}]}')
  ON DUPLICATE KEY UPDATE valor = VALUES(valor);

INSERT INTO contenido (clave, valor) VALUES ('macrobot', '{"titulo":"Celdas Robóticas","subtitulo":"Celdas Robóticas","tabs":[{"nombre":"Celdas de Paletizado","desc":"Acomodo, ordenamiento y estiba automatizada de cajas o productos terminados sobre tarimas. Optimizan la logística al final de la línea, reducen tiempos de embarque y eliminan el esfuerzo físico del personal.","images":["assets\\/images\\/general\\/celdas.webp","assets\\/images\\/general\\/img1.webp"]},{"nombre":"Celdas de Alimentación","desc":"Suministro constante, orientación y posicionamiento de componentes hacia máquinas de proceso de forma autónoma. Garantizan un flujo de producción continuo e ininterrumpido mediante manipulación robótica de alta velocidad.","images":["assets\\/images\\/general\\/img1.webp","assets\\/images\\/general\\/img2.webp"]},{"nombre":"Celdas con Sistema de Visión","desc":"Robótica inteligente integrada con cámaras industriales para identificar la posición y orientación de piezas en movimiento. Permite operaciones de sujeción, ensamble y manipulación altamente adaptativas.","images":["assets\\/images\\/general\\/img2.webp","assets\\/images\\/general\\/img3.webp"]},{"nombre":"Celdas de Soldadura","desc":"Unión automatizada de componentes metálicos mediante procesos MIG, TIG o por puntos. Garantizan cordones de alta resistencia, acabados homogéneos y una optimización rigurosa en el consumo de materiales.","images":["assets\\/images\\/general\\/img3.webp","assets\\/images\\/general\\/img1.webp"]},{"nombre":"Corte Láser de Pieza Metálica","desc":"Combinación de la flexibilidad de un brazo robótico con la potencia de un cabezal láser. Permite el contorneado, perforado y corte de precisión en geometrías metálicas tridimensionales complejas.","images":["assets\\/images\\/general\\/celdas.webp","assets\\/images\\/general\\/img1.webp"]}]}')
  ON DUPLICATE KEY UPDATE valor = VALUES(valor);

INSERT INTO contenido (clave, valor) VALUES ('maqinspe', '{"titulo":"Máquinas de Inspección","subtitulo":"Inspección","tabs":[{"nombre":"Inspección 3D","desc":"Escaneo óptico y láser para la reconstrucción tridimensional de piezas en tiempo real. Permite realizar análisis dimensionales exhaustivos y comparaciones contra el modelo CAD para asegurar una manufactura libre de desviaciones.","images":["assets\\/images\\/general\\/inspeccion.webp","assets\\/images\\/general\\/img1.webp"]},{"nombre":"Código de Barras 2D-3D","desc":"Lectura, decodificación y validación de calidad de códigos bidimensionales y tridimensionales grabados en superficies. Asegura el rastreo y la trazabilidad total del producto a lo largo de toda la cadena de suministro.","images":["assets\\/images\\/general\\/img1.webp","assets\\/images\\/general\\/img2.webp"]},{"nombre":"Geometría y Textura","desc":"Evaluación simultánea de formas complejas y rugosidad superficial en estaciones ópticas. Garantiza que el acabado exterior cumpla con las especificaciones exactas de fricción, estética y ensamble requeridas.","images":["assets\\/images\\/general\\/img2.webp","assets\\/images\\/general\\/img3.webp"]},{"nombre":"Espesor, Área y Altura","desc":"Medición volumétrica y de perfiles de elevación en componentes de alta precisión. Ideal para el control de calidad en la aplicación de selladores, dosificación de fluidos, cordones de soldadura y microelectrónica.","images":["assets\\/images\\/general\\/img3.webp","assets\\/images\\/general\\/img1.webp"]},{"nombre":"Acabado, Presencia y Marcas","desc":"Verificación final del acabado superficial, de la presencia correcta de todos los componentes y de la validación de marcas, logotipos y números de serie. Detecta piezas faltantes y defectos estéticos antes del empaque, asegurando un producto completo y conforme.","images":["assets\\/images\\/general\\/inspeccion.webp","assets\\/images\\/general\\/img1.webp"]}]}')
  ON DUPLICATE KEY UPDATE valor = VALUES(valor);

INSERT INTO contenido (clave, valor) VALUES ('maqindus', '{"titulo":"Maquinados Industriales","subtitulo":"Manufactura","tabs":[{"nombre":"Diseño 2D y 3D de Dispositivos","desc":"Modelado tridimensional y desarrollo de planos técnicos para herramentales y mecanismos. Aseguramos la viabilidad funcional, la ergonomía y la precisión geométrica de cada dispositivo antes de iniciar su fabricación.","images":["assets\\/images\\/products\\/maq.webp","assets\\/images\\/general\\/img1.webp"]},{"nombre":"Fabricación de Piezas Mecánicas","desc":"Manufactura de componentes de precisión mediante torneado, fresado y maquinado CNC en diversos materiales. Garantizamos el cumplimiento estricto de tolerancias dimensionales y los acabados superficiales requeridos.","images":["assets\\/images\\/products\\/maq2.webp","assets\\/images\\/general\\/img1.webp"]},{"nombre":"Diseño y Fabricación de Fixture","desc":"Creación de dispositivos de sujeción a la medida para optimizar procesos de ensamble, soldadura o inspección. Aseguran la repetibilidad operativa, mantienen la alineación exacta y reducen los tiempos de ciclo.","images":["assets\\/images\\/products\\/maq3.webp","assets\\/images\\/general\\/img1.webp"]}]}')
  ON DUPLICATE KEY UPDATE valor = VALUES(valor);

